/*
UNIVERSIDADE CRUZEIRO DO SUL
CURSO DE TECNOLOGIA EM ANÁLISE E 
DESENVOLVIMENTO DE SISTEMAS

TRABALHO IV
DISCIPLINA: MODELAGEM DE BANCO DE DADOS
BANCO DE DADOS PARA POUSADAS

PROFESSORES:
DOUGLAS ALMENDRO
BAGNER DA SILVA

TUTORES:
MARCONE MARINHO
FABIANA SABAI RODRIGUES
THIAGO SAULO VIEIRA THIAGO

ALUNO: LUIZ FERNANDO QUARESMA CAMPOS

TECNOLOGIA: BANCO DE DADOS MYSQL
*/

--
-- Banco de dados: `hospedapp`
-- 


-- Cria as tabelas

CREATE TABLE `hospedagem` (
  `HOSP_CD_ID` int(20) NOT NULL,
  `HOSP_CD_UNIDADE` int(9) NOT NULL,
  `HOSP_CD_PESSOA_FISICA` varchar(20) NOT NULL,
  `HOSP_CD_PESSOA_JURIDICA` varchar(9) NOT NULL,
  `HOSP_CD_TIPO` varchar(18) NOT NULL,
  `HOSP_DT_INICIO_RESERVA_DATA` datetime NOT NULL,
  `HOSP_DT_FIM_RESERVA_DATA` datetime NOT NULL,
  `HOSP_DT_CHECKIN_DATA` datetime NOT NULL,
  `HOSP_DT_PREVIA_CHECKOUT_DATA` date NOT NULL,
  `HOSP_DT_CHECKOUT_DATA` datetime NOT NULL,
  `HOSP_QT_DIAS_HOSPEDADO` varchar(4) NOT NULL,
  `HOSP_NU_ACOMPANHANTES` int(3) NOT NULL,
  `HOSP_CD_QUARTO` varchar(22) NOT NULL,
  `HOSP_VL_DIARIA_QUARTO` varchar(9) NOT NULL,
  `HOSP_CD_PROMOCAO` varchar(22) NOT NULL,
  `HOSP_CD_TIPO_PROMOCAO` varchar(2) NOT NULL,
  `HOSP_CD_TIPO_CONTAGEM_DIARIAS` varchar(1) NOT NULL,
  `HOSP_QT_PERCENTUAL_DESCONTO` int(3) NOT NULL,
  `HOSP_VL_DEBITO_HOSPEDAGEM` varchar(22) NOT NULL,
  `HOSP_VL_DEBITO_PEDIDOS` varchar(22) NOT NULL,
  `HOSP_VL_DEBITO_TOTAL` varchar(22) NOT NULL,
  `HOSP_QT_PERCENTUAL_SINAL` varchar(3) NOT NULL,
  `HOSP_VL_SINAL_PAGO` varchar(22) NOT NULL,
  `HOSP_DT_PAGAMENTO_SINAL_DATA` datetime NOT NULL,
  `HOSP_VL_TOTAL_PAGO` varchar(22) NOT NULL,
  `HOSP_CD_FORMA_PAGAMENTO` varchar(9) NOT NULL,
  `HOSP_TX_DESCRICAO_PAGAMENTO` varchar(256) NOT NULL,
  `HOSP_NU_NOTA_FISCAL` varchar(80) NOT NULL,
  `HOSP_DT_VENCIMENTO` varchar(40) NOT NULL,
  `HOSP_CD_QUITADO` varchar(1) NOT NULL,
  `HOSP_DT_PAGAMENTO_DATA` datetime NOT NULL,
  `HOSP_CD_STATUS` varchar(2) NOT NULL,
  `HOSP_DT_MES` varchar(2) NOT NULL,
  `HOSP_DT_ANO` varchar(4) NOT NULL,
  `HOSP_TX_REGISTRO_RETIFICACOES` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;


CREATE TABLE `pagamento` (
  `PAGM_CD_ID` int(22) NOT NULL,
  `PAGM_CD_UNIDADE` int(9) NOT NULL,
  `PAGM_TX_DESCRICAO` varchar(80) NOT NULL,
  `PAGM_CD_TIPO` varchar(9) NOT NULL,
  `PAGM_CD_HOSPEDAGEM` varcV    HGHUBHhar(9) NOT NULL,
  `PAGM_CD_PESSOA_FISICA` varchar(9) NOT NULL,
  `PAGM_CD_PESSOA_JURIDICA` varchar(9) NOT NULL,
  `PAGM_VL_VALOR_PAGO` varchar(12) NOT NULL,
  `PAGM_DT_PAGAMENTO` datetime NOT NULL,
  `PAGM_CD_STATUS` varchar(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;


CREATE TABLE `pedido` (
  `PEDI_CD_ID` int(50) NOT NULL,
  `PEDI_CD_UNIDADE` int(9) NOT NULL,
  `PEDI_CD_ID_HOSPEDAGEM` varchar(50) NOT NULL,
  `PEDI_CD_PESSOA_FISICA` varchar(12) NOT NULL,
  `PEDI_CD_PESSOA_JURIDICA` varchar(12) NOT NULL,
  `PEDI_TX_DESCRICAO` varchar(256) NOT NULL,
  `PEDI_CD_TIPO` varchar(40) NOT NULL,
  `PEDI_DATA_HORA` datetime NOT NULL,
  `PEDI_VL_VALOR` varchar(25) NOT NULL,
  `PEDI_NU_QUANTIDADE` varchar(12) NOT NULL,
  `PEDI_CD_TIPO_FREQUENCIA` varchar(12) NOT NULL,
  `PEDI_NU_DIAS` varchar(4) NOT NULL,
  `PEDI_VL_VALOR_DEBITO_TOTAL` varchar(22) NOT NULL,
  `PEDI_VL_VALOR_PAGAMENTO` varchar(22) NOT NULL,
  `PEDI_DT_PAGAMENTO_DATA` datetime NOT NULL,
  `PEDI_CD_QUITADO` varchar(1) NOT NULL,
  `PEDI_CD_STATUS` varchar(1) NOT NULL,
  `PEDI_TX_REGISTRO_RETIFICACOES` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;


CREATE TABLE `pessoa_fisica` (
  `PESF_CD_ID` int(22) NOT NULL,
  `PESF_CD_UNIDADE` int(9) NOT NULL,
  `PESF_NM_NOME` varchar(160) NOT NULL,
  `PESF_CD_SEXO` varchar(1) NOT NULL,
  `PESF_CD_CPF` varchar(20) NOT NULL,
  `PESF_CD_RG` varchar(20) NOT NULL,
  `PESF_CD_ORGAO_EXPEDIDOR_RG` varchar(12) NOT NULL,
  `PESF_DT_DATA_NASCIMENTO` date NOT NULL,
  `PESF_CD_EMPRESA` varchar(22) NOT NULL,
  `PESF_TX_PROFISSAO` varchar(160) NOT NULL,
  `PESF_ED_RUA` varchar(220) NOT NULL,
  `PESF_ED_NUMERO` varchar(9) NOT NULL,
  `PESF_ED_COMPLEMENTO` varchar(160) NOT NULL,
  `PESF_ED_BAIRRO` varchar(160) NOT NULL,
  `PESF_ED_CEP` varchar(20) NOT NULL,
  `PESF_ED_CIDADE` varchar(160) NOT NULL,
  `PESF_ED_ESTADO` varchar(2) NOT NULL,
  `PESF_ED_EMAIL` varchar(160) NOT NULL,
  `PESF_ED_TELEFONE_FIXO` varchar(60) NOT NULL,
  `PESF_ED_TELEFONE_CELULAR` varchar(60) NOT NULL,
  `PESF_CD_DATA_INCLUSAO` date NOT NULL,
  `PES_CD_STATUS` varchar(1) NOT NULL,
  `PESS_QT_CREDITO` varchar(22) NOT NULL,
  `PESF_CD_TIPO_PESSOA` varchar(1) NOT NULL,
  `PESF_CD_SENHA` varchar(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;


CREATE TABLE `pessoa_juridica` (
  `PEJU_CD_ID` int(20) NOT NULL,
  `PEJU_CD_UNIDADE` int(9) NOT NULL,
  `PEJU_NM_RAZAO_SOCIAL` varchar(220) NOT NULL,
  `PEJU_NM_NOME` varchar(220) NOT NULL,
  `PEJU_CD_CNPJ` varchar(22) NOT NULL,
  `PEJU_ED_RUA` varchar(200) NOT NULL,
  `PEJU_ED_NUMERO_ENDERECO` varchar(9) NOT NULL,
  `PEJU_ED_COMPLEMENTO` varchar(80) NOT NULL,
  `PEJU_ED_BAIRRO` varchar(60) NOT NULL,
  `PEJU_ED_CIDADE` varchar(60) NOT NULL,
  `PEJU_ED_CEP` varchar(20) NOT NULL,
  `PEJU_ED_ESTADO` varchar(2) NOT NULL,
  `PEJU_ED_EMAIL` varchar(160) NOT NULL,
  `PEJU_ED_TELEFONE` varchar(40) NOT NULL,
  `PEJU_ED_CELULAR` varchar(40) NOT NULL,
  `PEJU_DT_DATA_INCLUSAO` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;


CREATE TABLE `promocao` (
  `PROM_CD_ID` int(22) NOT NULL,
  `PROM_CD_UNIDADE` int(9) NOT NULL,
  `PROM_CD_EMPRESA` varchar(22) NOT NULL,
  `PROM_NM_NOME` varchar(160) NOT NULL,
  `PROM_VL_PERCENTUAL_DESCONTO` varchar(3) NOT NULL,
  `PROM_CD_TIPO` varchar(1) NOT NULL,
  `PROM_CD_CONTABILIZACAO_NUMERO_DIARIAS` varchar(1) NOT NULL,
  `PROM_CD_STATUS` varchar(3) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;


CREATE TABLE `quarto` (
  `QURT_CD_ID` int(9) NOT NULL,
  `QURT_CD_UNIDADE` int(9) NOT NULL,
  `QURT_NM_NOME` varchar(160) NOT NULL,
  `QURT_TX_PROPRIEDADES` varchar(260) NOT NULL,
  `QURT_CD_TIPO` varchar(9) NOT NULL,
  `QURT_QT_MAXIMO_OCUPANTES` int(3) NOT NULL,
  `QUET_VL_VALOR_DIARIA` varchar(9) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;


CREATE TABLE `tipo_hospedagem` (
  `TIPH_CD_ID` int(9) NOT NULL,
  `TIPH_CD_ID_TEXTO` varchar(22) NOT NULL,
  `TIPH_NM_TIPO_HOSPEDAGEM` varchar(160) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;



CREATE TABLE `tipo_pagamento` (
  `TPAG_CD_ID` int(9) NOT NULL,
  `TPAG_TX_DESCRICAO` varchar(60) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;


CREATE TABLE `tipo_pedido` (
  `TPED_CD_ID` int(25) NOT NULL,
  `TPED_CD_UNIDADE` int(9) NOT NULL,
  `TPED_TX_DESCRICAO` varchar(256) NOT NULL,
  `TPED_CD_CATEGORIA` varchar(80) NOT NULL,
  `TPED_CD_QUANTIDADE_FREQUENCIA` varchar(9) NOT NULL,
  `TPED_VL_VALOR` varchar(25) NOT NULL,
  `TPED_CD_BAIXA_ESTOQUE` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;


CREATE TABLE `unidade` (
  `UNID_CD_ID` int(9) NOT NULL,
  `UNID_NM_NOME` varchar(180) NOT NULL,
  `UNID_NM_TITULO` varchar(180) NOT NULL,
  `UNID_ED_PASTA` varchar(40) NOT NULL,
  `UNID_CD_CNPJ` varchar(22) NOT NULL,
  `UNID_ED_RUA` varchar(180) NOT NULL,
  `UNID_ED_NUMERO` varchar(18) NOT NULL,
  `UNID_ED_COMPLEMENTOS` varchar(180) NOT NULL,
  `UNID_ED_BAIRRO` varchar(180) NOT NULL,
  `UNID_ED_CIDADE` varchar(180) NOT NULL,
  `UNID_ED_UF` varchar(11) NOT NULL,
  `UNID_ED_EMAIL` varchar(80) NOT NULL,
  `UNID_ED_SITE` varchar(180) NOT NULL,
  `UNID_ED_TELEFONE` varchar(80) NOT NULL,
  `UNID_ED_CELULAR` varchar(80) NOT NULL,
  `UNID_ED_LOGOTIPO` varchar(180) NOT NULL,
  `UNID_PREVALECER_DADOS_SISTEMA` varchar(1) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE `estoque` (
  `ESTQ_CD_ID` int(22) NOT NULL,
  `ESTQ_CD_UNIDADE` int(9) NOT NULL,
  `ESTQ_NM_NOME` varchar(240) NOT NULL,
  `ESTQ_CD_UNIDADE_MEDIDA` varchar(9) NOT NULL,
  `ESTQ_QT_QUANTIDADE` int(40) NOT NULL,
  `ESTQ_CD_CATEGORIA` varchar(22) NOT NULL,
  `ESTQ_DT_DATA_HORA_INCLUSAO` datetime NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE `estoque_categoria` (
  `ESCA_CD_ID` int(9) NOT NULL,
  `ESCA_NM_CATEGORIA` text NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE `estoque_controle` (
  `CEST_CD_ID` int(50) NOT NULL,
  `CEST_CD_UNIDADE` int(9) NOT NULL,
  `CEST_CD_TIPO_MOVIMENTO` varchar(25) NOT NULL,
  `CEST_ID_PRODUTO` varchar(25) NOT NULL,
  `CEST_NM_PRODUTO` varchar(250) NOT NULL,
  `CEST_QT_QUANTIDADE` int(12) NOT NULL,
  `CEST_TX_UNIDADE_MEDIDA` varchar(12) NOT NULL,
  `CEST_VL_VALOR_INVESTIDO` varchar(22) NOT NULL,
  `CEST_TX_OBSERVACAO` text NOT NULL,
  `CEST_DT_ENTRADA` datetime NOT NULL,
  `CEST_DT_MES` varchar(2) NOT NULL,
  `CEST_DT_ANO` varchar(4) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE `estoque_unidade_medica` (
  `UNME_CD_ID` int(9) NOT NULL,
  `UNME_NM_NOME` text NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE `forma_pagamento` (
  `FPAG_CD_ID` int(9) NOT NULL,
  `FPAG_NM_NOME` varchar(48) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;


-- Índices nas tabelas

ALTER TABLE `estoque`
  ADD PRIMARY KEY (`ESTQ_CD_ID`);

ALTER TABLE `estoque_categoria`
  ADD PRIMARY KEY (`ESCA_CD_ID`);

ALTER TABLE `forma_pagamento`
  ADD PRIMARY KEY (`FPAG_CD_ID`);

ALTER TABLE `hospedagem`
  ADD PRIMARY KEY (`HOSP_CD_ID`);

ALTER TABLE `pagamento`
  ADD PRIMARY KEY (`PAGM_CD_ID`);

ALTER TABLE `pedido`
  ADD PRIMARY KEY (`PEDI_CD_ID`);
COMMIT;

